version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/awx/ui"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "production"
    reviewers:
      - "AlexSCorey"
      - "keithjgrant"
      - "kialam"
      - "mabashian"
      - "marshmalien"
      - "nixocio"
    labels:
      - "component:ui"
      - "dependencies"
    target-branch: "devel"
