---
blank_issues_enabled: true
contact_links:
  - name: For debugging help or technical support
    url: https://github.com/ansible/awx#get-involved
    about: For general debugging or technical support please see the Get Involved section of our readme.
  - name: ğŸ“ Ansible Code of Conduct
    url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_template_chooser
    about: AWX uses the Ansible Code of Conduct; â¤ Be nice to other members of the community. â˜® Behave.
  - name: ğŸ’¼ For Enterprise
    url: https://www.ansible.com/products/engine?utm_medium=github&utm_source=issue_template_chooser
    about: Red Hat offers support for the Ansible Automation Platform
