---
# Structure for the Elastic Stack docker configuration came from docker-elk:
# https://github.com/deviantony/docker-elk
# docker-elk is under the MIT License,
# a copy of its license is provided in docs/licenses/docker-elk.txt
# contents modified

version: '2'
services:

  # Components of ELK stack for logging
  elasticsearch:
    build: elastic/elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      # networks: # add back in when a connection to tower_tools is possible
      #   - docker_elk

  logstash:
    build: elastic/logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elastic/logstash/config:/etc/logstash/conf.d
    ports:
      - "8085:8085"
    links:
      - elasticsearch
    # networks:
    #   - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: elastic/kibana/
    volumes:
      - ./elastic/kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    # networks:
    #   - docker_elk
    depends_on:
      - elasticsearch

# networks:
#   docker_elk:
#     driver: bridge
