- hosts: all
  vars:
    scan_use_checksum: false
    scan_use_recursive: false
  tasks:

    - name: "Scan packages (Unix/Linux)"
      scan_packages:
        os_family: '{{ ansible_os_family }}'
      when: ansible_os_family != "Windows"
    - name: "Scan services (Unix/Linux)"
      scan_services:
      when: ansible_os_family != "Windows"
    - name: "Scan files (Unix/Linux)"
      scan_files:
        paths: '{{ scan_file_paths }}'
        get_checksum: '{{ scan_use_checksum }}'
        recursive: '{{ scan_use_recursive }}'
      when: scan_file_paths is defined and ansible_os_family != "Windows"
    - name: "Scan Insights for Machine ID (Unix/Linux)"
      scan_insights:
      when: ansible_os_family != "Windows"

    - name: "Scan packages (Windows)"
      win_scan_packages:
      when: ansible_os_family == "Windows"
    - name: "Scan services (Windows)"
      win_scan_services:
      when: ansible_os_family == "Windows"
    - name: "Scan files (Windows)"
      win_scan_files:
        paths: '{{ scan_file_paths }}'
        get_checksum: '{{ scan_use_checksum }}'
        recursive: '{{ scan_use_recursive }}'
      when: scan_file_paths is defined and ansible_os_family == "Windows"

