---

- name: set tls verification options
  set_fact:
    tls_options: "--tls-verify={{ build_tool_tls_verify | default(true) }}"
  when: build_tool != "docker"

- name: Authenticate with Docker registry if registry password given
  command: "{{ build_tool }} login {{  tls_options | default('') }} -u {{ docker_registry_username }} -p {{ docker_registry_password }} {{ docker_registry }}"
  when: docker_registry is defined and docker_registry_password is defined and build_tool
  ignore_errors: true
  no_log: true

- name: Remove local images to ensure proper push behavior
  block:
    - name: Remove awx image
      command: "{{ build_tool }} rmi {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{ awx_version }}"
      ignore_errors: true

- name: Tag Container Images
  block:
    - name: Tag awx image to registry
      command: "{{ build_tool }} tag {{ awx_image }} {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{ item }}"
      with_items:
        - "latest"
        - "{{ awx_version }}"

- name: Push Container Images
  block:
    - name: Push awx image to registry
      command: "{{ build_tool }} push {{ tls_options | default('') }} {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{ item }}"
      with_items:
        - "latest"
        - "{{ awx_version }}"


- name: Set full image path for Registry
  set_fact:
    awx_docker_actual_image: >-
      {{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}:{{ awx_version }}
