---
version: '2'
services:
  haproxy:
    build:
      context: ./docker-compose
      dockerfile: Dockerfile-haproxy
    container_name: tools_haproxy_1
    depends_on:
      - "awx-1"
      - "awx-2"
      - "awx-3"
    ports:
      - "8013:8013"
      - "8043:8043"
      - "1936:1936"
  awx-1:
    user: ${CURRENT_UID}
    container_name: tools_awx_1_1
    privileged: true
    image: ${DEV_DOCKER_TAG_BASE}/awx_devel:${TAG}
    hostname: awx-1
    environment:
      CURRENT_UID:
      SDB_HOST: 0.0.0.0
      SDB_PORT: 5899
      AWX_GROUP_QUEUES: alpha,tower
    command: launch_awx.sh
    working_dir: "/awx_devel"
    volumes:
      - "../:/awx_devel"
      - "./redis/redis_socket_ha_1:/var/run/redis/"
      - "./docker-compose/supervisor.conf:/etc/supervisord.conf"
    ports:
      - "5899-5999:5899-5999"
  awx-2:
    user: ${CURRENT_UID}
    container_name: tools_awx_2_1
    privileged: true
    image: ${DEV_DOCKER_TAG_BASE}/awx_devel:${TAG}
    hostname: awx-2
    command: launch_awx.sh
    working_dir: "/awx_devel"
    environment:
      CURRENT_UID:
      SDB_HOST: 0.0.0.0
      SDB_PORT: 7899
      AWX_GROUP_QUEUES: bravo,tower
    volumes:
      - "../:/awx_devel"
      - "./redis/redis_socket_ha_2:/var/run/redis/"
      - "./docker-compose/supervisor.conf:/etc/supervisord.conf"
    ports:
      - "7899-7999:7899-7999"
  awx-3:
    user: ${CURRENT_UID}
    container_name: tools_awx_3_1
    privileged: true
    image: ${DEV_DOCKER_TAG_BASE}/awx_devel:${TAG}
    hostname: awx-3
    command: launch_awx.sh
    working_dir: "/awx_devel"
    environment:
      CURRENT_UID:
      SDB_HOST: 0.0.0.0
      SDB_PORT: 8899
      AWX_GROUP_QUEUES: charlie,tower
    volumes:
      - "../:/awx_devel"
      - "./redis/redis_socket_ha_3:/var/run/redis/"
      - "./docker-compose/supervisor.conf:/etc/supervisord.conf"
    ports:
      - "8899-8999:8899-8999"
  redis_1:
    user: ${CURRENT_UID}
    image: redis:latest
    container_name: tools_redis_1_1
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/redis_socket_ha_1:/var/run/redis/"
  redis_2:
    user: ${CURRENT_UID}
    image: redis:latest
    container_name: tools_redis_2_1
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/redis_socket_ha_2:/var/run/redis/"
  redis_3:
    user: ${CURRENT_UID}
    image: redis:latest
    container_name: tools_redis_3_1
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/redis_socket_ha_3:/var/run/redis/"
  postgres:
    image: postgres:10
    container_name: tools_postgres_1
