version: '2'
services:
  # Primary AWX Development Container
  awx:
    user: ${CURRENT_UID}
    image: ${DEV_DOCKER_TAG_BASE}/awx_devel:${TAG}
    container_name: tools_awx_1
    hostname: awx
    command: /start_development.sh
    environment:
      CURRENT_UID:
      OS:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_VHOST: /
      SDB_HOST: 0.0.0.0
      SDB_PORT: 7899
      AWX_GROUP_QUEUES: tower
    ports:
      - "8888:8888"
      - "8080:8080"
      - "8013:8013"
      - "8043:8043"
      - "6899:6899"  # default port range for sdb-listen
      - "7899-7999:7899-7999"  # default port range for sdb-listen
    links:
      - postgres
      - memcached
      - rabbitmq
    #   - sync
    # volumes_from:
    #   - sync
    working_dir: "/awx_devel"
    volumes:
      - "../:/awx_devel"
    privileged: true
  # A useful container that simply passes through log messages to the console
  # helpful for testing awx/tower logging
  # logstash:
  #   build:
  #     context: ./docker-compose
  #     dockerfile: Dockerfile-logstash

  # Postgres Database Container
  postgres:
    image: postgres:10
    container_name: tools_postgres_1
    ports:
        - "5432:5432"
  memcached:
    image: memcached:alpine
    container_name: tools_memcached_1
    ports:
      - "11211:11211"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tools_rabbitmq_1
    ports:
      - "15672:15672"
