---
- name: Add a label to Controller
  label:
    name: "{{ __controller_label_item.name | mandatory }}"
    new_name: "{{ __controller_label_item.new_name | default(omit, true) }}"
    organization: "{{ __controller_label_item.organization | mandatory }}"
    state: "{{ __controller_label_item.state | default(controller_state | default('present')) }}"

    # Role Standard Options
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    controller_host: "{{ controller_hostname | default(omit, true) }}"
    controller_username: "{{ controller_username | default(omit, true) }}"
    controller_password: "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit, true) }}"
    validate_certs: "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_labels }}"
  loop_control:
    loop_var: __controller_label_item
  no_log: "{{ controller_configuration_labels_secure_logging }}"
  async: 1000
  poll: 0
  register: __controller_label_job_async
  changed_when: not __controller_label_job_async.changed
  vars:
    ansible_async_dir: '/tmp/.ansible_async'

- name: "Configure Labels | Wait for finish the Label creation"
  ansible.builtin.async_status:
    jid: "{{ __controller_label_job_async_results_item.ansible_job_id }}"
  register: __controller_label_job_async_result
  until: __controller_label_job_async_result.finished
  retries: "{{ controller_configuration_labels_async_retries }}"
  delay: "{{ controller_configuration_labels_async_delay }}"
  loop: "{{ __controller_label_job_async.results }}"
  loop_control:
    loop_var: __controller_label_job_async_results_item
  when: __controller_label_job_async_results_item.ansible_job_id is defined
  no_log: "{{ controller_configuration_labels_secure_logging }}"
  vars:
    ansible_async_dir: '/tmp/.ansible_async'
...
