---
version: '2'
services:
  unit-tests:
    build:
      context: ../../../
      dockerfile: tools/docker-compose/unit-tests/Dockerfile
    image: gcr.io/ansible-tower-engineering/unit-test-runner:latest
    environment:
      SWIG_FEATURES: "-cpperraswarn -includeall -I/usr/include/openssl"
      TEST_DIRS: awx/main/tests/functional awx/main/tests/unit
    command: ["make test"]
    volumes:
      - ../../../:/tower_devel
